*** Settings ***
Documentation     Fichier ressource pour ouvrir 
...               Keywords defined here can be used where this Keywords.resource in loaded.
Library           Testsuite.py


*** Keywords ***
Ouverture du menu de navigation
    Verification
    Appuyer

# Ouverture menu profil de connexion
#     Vérification existence du bouton menu profil de connexion
#     Appuyer boutton profil de connexion
